/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productbacklog;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miria
 */
public class CalculoPFNA extends javax.swing.JFrame {

    /**
     * Creates new form CalculoPFNA
     */
    private HashMap<String, Complejidad> c;
    private int pfna;

    DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public CalculoPFNA(HashMap c) {
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        this.pfna = 0;
        DrawingTabla();

    }

    private void DrawingTabla() {
        jTable1.setModel(tabla);

        String[] col = {"Descripción", "Sencilla", "Media", "Compleja", "Total P.F"};
        tabla.setColumnIdentifiers(col);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);

        fillTabla();
    }

    private void fillTabla() {

        Complejidad com;

        com = c.get("EE");
        if (com != null) {
            int total = 0;
            total += com.getS() * 3;
            total += com.getM() * 4;
            total += com.getC() * 6;
            this.pfna += total;
            tabla.addRow(new String[]{com.tipo, String.valueOf(com.getS()) + " x " + "3", String.valueOf(com.getM()) + " x " + "4", String.valueOf(com.getC()) + " x " + "6", String.valueOf(total)});
        }
        com = c.get("SE");

        if (com != null) {
            int total = 0;
            total += com.getS() * 4;
            total += com.getM() * 5;
            total += com.getC() * 7;
            this.pfna += total;
            tabla.addRow(new String[]{com.tipo, String.valueOf(com.getS()) + " x " + "4", String.valueOf(com.getM()) + " x " + "5", String.valueOf(com.getC()) + " x " + "7", String.valueOf(total)});
        }

        com = c.get("FLI");
        if (com != null) {
            int total = 0;
            total += com.getS() * 7;
            total += com.getM() * 10;
            total += com.getC() * 15;
            this.pfna += total;
            tabla.addRow(new String[]{com.tipo, String.valueOf(com.getS()) + " x " + "7", String.valueOf(com.getM()) + " x " + "10", String.valueOf(com.getC()) + " x " + "15", String.valueOf(total)});
        }
        com = c.get("FLE");
        if (com != null) {
            int total = 0;
            total += com.getS() * 5;
            total += com.getM() * 7;
            total += com.getC() * 10;
            this.pfna += total;
            tabla.addRow(new String[]{com.tipo, String.valueOf(com.getS()) + " x " + "5", String.valueOf(com.getM()) + " x " + "7", String.valueOf(com.getC()) + " x " + "10", String.valueOf(total)});
        }
        com = c.get("CE");
        if (com != null) {
            int total = 0;
            total += com.getS() * 3;
            total += com.getM() * 4;
            total += com.getC() * 6;
            this.pfna += total;
            tabla.addRow(new String[]{com.tipo, String.valueOf(com.getS()) + " x " + "3", String.valueOf(com.getM()) + " x " + "4", String.valueOf(com.getC()) + " x " + "6", String.valueOf(total)});
        }

        tabla.addRow(new String[]{"", "", "", "", String.valueOf(this.pfna)});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AjusteInfluencia ven = new AjusteInfluencia();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CalculoPFNA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
