/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productbacklog;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario1
     */
    private static ArrayList<ElementosFuncionales> tElementos;

    public Formulario1() {
        initComponents();
        setLocationRelativeTo(null);
        lVar5.setVisible(false);
        t4.setVisible(false);
        tElementos = new ArrayList<>();

    }
    
    public static ArrayList<ElementosFuncionales> getElementos(){
        return tElementos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lVar1 = new javax.swing.JLabel();
        lVar2 = new javax.swing.JLabel();
        lVar3 = new javax.swing.JLabel();
        lVar4 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        lVar5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elementos Funcionales");
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lVar1.setText("Grupo Logico");
        getContentPane().add(lVar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lVar2.setText("Tipo de Componente");
        getContentPane().add(lVar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lVar3.setText("Numero de Ficheros");
        getContentPane().add(lVar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lVar4.setText("Numero de Datos Elementales");
        getContentPane().add(lVar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        b1.setText("Añadir");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        b2.setText("Enviar");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EE", "SE", "CE", "FLI", "FLE" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 105, -1, -1));

        lVar5.setText("Numero de Datos Elementales de Salida");
        getContentPane().add(lVar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        t1.setMaximumSize(new java.awt.Dimension(65, 28));
        t1.setMinimumSize(new java.awt.Dimension(65, 28));
        t1.setPreferredSize(new java.awt.Dimension(65, 28));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 55, -1, -1));

        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setMaximumSize(new java.awt.Dimension(30, 28));
        t2.setMinimumSize(new java.awt.Dimension(30, 28));
        t2.setPreferredSize(new java.awt.Dimension(30, 28));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 155, -1, -1));

        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setMaximumSize(new java.awt.Dimension(30, 28));
        t3.setMinimumSize(new java.awt.Dimension(30, 28));
        t3.setPreferredSize(new java.awt.Dimension(30, 28));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 205, -1, -1));

        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setMaximumSize(new java.awt.Dimension(30, 28));
        t4.setMinimumSize(new java.awt.Dimension(30, 28));
        t4.setPreferredSize(new java.awt.Dimension(30, 28));
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 255, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        if (cb1.getSelectedItem().toString().equals("CE")) {
            lVar4.setSize(240, 14);
            lVar4.setText("Numero de Datos Elementales de Entrada");
            lVar5.setVisible(true);
            setLayout(null);
            b1.setLocation(170, 340);
            t3.setLocation(300, 205);
            t4.setLocation(300, 255);
            t4.setVisible(true);

        } else {
            lVar4.setSize(189, 14);
            lVar4.setText("Numero de Datos Elementales");
            lVar5.setVisible(false);
            setLayout(null);
            b1.setLocation(170, 300);
            t4.setVisible(false);
            t3.setLocation(270, 205);
            t4.setLocation(270, 255);

        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        ElementosFuncionales aux = new ElementosFuncionales();
        if (t1.getText().equals("")|| t2.getText().equals("") || t3.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Revisa que los campos no esten vacios o con valores incorrectos","Error",2);
        }else{
            aux.setNomGrupoLogico(t1.getText());
            aux.setNomTipoComponente(cb1.getSelectedItem().toString());
            aux.setnFicheros(Integer.parseInt(t2.getText()));
            aux.setnDatosElementalesEnt(Integer.parseInt(t3.getText()));
            if (!t4.getText().equals("")){
                aux.setnDatosElementalesSal(Integer.parseInt(t4.getText()));
            }
            
            tElementos.add(aux);
        }
        
        //HACER COMPROBACIONES Y VALIDACIONES
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (tElementos.isEmpty()) {
            ElementosFuncionales aux = new ElementosFuncionales();
        if (t1.getText().equals("")|| t2.getText().equals("") || t3.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Revisa que los campos no esten vacios o con valores incorrectos","Error",2);
        }else{
            aux.setNomGrupoLogico(t1.getText());
            aux.setNomTipoComponente(cb1.getSelectedItem().toString());
            aux.setnFicheros(Integer.parseInt(t2.getText()));
            aux.setnDatosElementalesEnt(Integer.parseInt(t3.getText()));
            if (!t4.getText().equals("")){
                aux.setnDatosElementalesSal(Integer.parseInt(t4.getText()));
            }
            
            tElementos.add(aux);
        }
            //METER AQUI EL METODO DE AÑADIR CON SUS COMPROBACIONES
        }else{
            //CAMBIAR DE VENTANA Y CERRAR LA ACTUAL
            CalculoComplejidad ven = new CalculoComplejidad(tElementos);
            ven.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_b2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel lVar1;
    private javax.swing.JLabel lVar2;
    private javax.swing.JLabel lVar3;
    private javax.swing.JLabel lVar4;
    private javax.swing.JLabel lVar5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
